apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: deploy
    labels:
        app: deploy
spec:
    selector:
        matchLabels:
            app: deploy
    replicas: 2
    template:
        metadata:
            name: deploy
            labels:
                app: deploy
        spec:
            containers:
                - name: deploy
                  image: venzel/deploy:latest
