apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: server-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        name: server
        kind: Deployment
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 25