apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy
    labels:
        app: deploy
spec:
    selector:
        matchLabels:
            app: deploy
    replicas: 10
    template:
        metadata:
            name: deploy
            labels:
                app: deploy
        spec:
            containers:
                - name: deploy
                  image: venzel/deploy:latest
                  
                  resources:
                        requests:
                            cpu: '0.05'
                            memory: 20Mi
                        limits:
                            cpu: '0.05'
                            memory: 25Mi
