apiVersion: v1
kind: Pod
metadata:
    name: deploy
    labels:
        app: deploy
spec:
    containers:
        - name: deploy
          image: venzel/deploy:latest

          resources:
            requests:
                cpu: '0.05'
                memory: 20Mi
            limits:
                cpu: '0.05'
                memory: 25Mi

